const express=require('express'),fs=require('fs'),path=require('path'),{spawn}=require('child_process'),crypto=require('crypto'),https=require('https');
const app=express(),PORT=process.env.PORT||3000,HOST=process.env.HOST||'0.0.0.0',ROOT=path.join(__dirname,'servers'),DB=path.join(__dirname,'servers.json');
fs.mkdirSync(ROOT,{recursive:true});if(!fs.existsSync(DB))fs.writeFileSync(DB,'[]');app.use(express.json({limit:'1mb'}));app.use(express.static(__dirname));
const readDB=()=>JSON.parse(fs.readFileSync(DB,'utf8')),writeDB=x=>fs.writeFileSync(DB,JSON.stringify(x,null,2));
function getPort(db){const used=new Set(db.map(x=>x.port));for(let p=25565;p<26000;p++)if(!used.has(p))return p;throw Error('No free ports')}
function getManifest(cb){https.get('https://piston-meta.mojang.com/mc/game/version_manifest_v2.json',r=>{let d='';r.on('data',x=>d+=x);r.on('end',()=>{try{cb(null,JSON.parse(d))}catch(e){cb(e)}})}).on('error',cb)}
function download(url,dest,cb){const f=fs.createWriteStream(dest);https.get(url,r=>{if(r.statusCode>=300&&r.statusCode<400&&r.headers.location)return download(r.headers.location,dest,cb);if(r.statusCode!==200)return cb(Error('download '+r.statusCode));r.pipe(f);f.on('finish',()=>f.close(cb))}).on('error',e=>{try{fs.unlinkSync(dest)}catch{}cb(e)})}
function ensureJar(version,cb){getManifest((e,m)=>{if(e)return cb(e);const v=m.versions.find(x=>x.id===version&&x.type==='release');if(!v)return cb(Error('unsupported release'));https.get(v.url,r=>{let d='';r.on('data',x=>d+=x);r.on('end',()=>{try{const j=JSON.parse(d),dest=path.join(ROOT,'server-'+version+'.jar');if(fs.existsSync(dest))return cb(null,dest);download(j.downloads.server.url,dest,x=>x?cb(x):cb(null,dest))}catch(x){cb(x)}})}).on('error',cb)})}
function alive(pid){if(!pid)return false;try{process.kill(pid,0);return true}catch{return false}}
app.get('/api/servers',(req,res)=>res.json(readDB().map(s=>({...s,online:alive(s.pid)}))));
app.post('/api/servers',(req,res)=>{const {name,version='26.2',type='Vanilla',mode='survival',maxPlayers=10,seed=''}=req.body||{};if(!name)return res.status(400).json({error:'name required'});if(version!=='26.2')return res.status(400).json({error:'starter supports 26.2'});const db=readDB(),id=crypto.randomUUID(),port=getPort(db),dir=path.join(ROOT,id);fs.mkdirSync(dir,{recursive:true});ensureJar(version,(e,jar)=>{if(e)return res.status(500).json({error:e.message});fs.writeFileSync(path.join(dir,'eula.txt'),'eula=true\n');fs.writeFileSync(path.join(dir,'server.properties'),`server-port=${port}\nmax-players=${Number(maxPlayers)||10}\ngamemode=${mode}\nmotd=${name}\nlevel-seed=${seed}\nonline-mode=true\n`);const child=spawn('java',['-Xms1G','-Xmx2G','-jar',jar,'nogui'],{cwd:dir});const publicHost=process.env.PUBLIC_HOST||'YOUR_DOMAIN';const rec={id,name,version,type,mode,maxPlayers,seed,port,ip:`${publicHost}:${port}`,pid:child.pid,dir};db.push(rec);writeDB(db);child.on('exit',()=>writeDB(readDB().map(s=>s.id===id?{...s,pid:null}:s)));res.json(rec)})});
app.post('/api/servers/:id/stop',(req,res)=>{const s=readDB().find(x=>x.id===req.params.id);if(!s)return res.status(404).json({error:'not found'});if(s.pid){try{process.kill(s.pid)}catch{}}res.json({ok:true})});
app.post('/api/servers/:id/start',(req,res)=>{const s=readDB().find(x=>x.id===req.params.id);if(!s)return res.status(404).json({error:'not found'});if(alive(s.pid))return res.json({ok:true,already:true});const jar=path.join(ROOT,'server-'+s.version+'.jar');if(!fs.existsSync(jar))return res.status(500).json({error:'server jar missing'});const child=spawn('java',['-Xms1G','-Xmx2G','-jar',jar,'nogui'],{cwd:s.dir});s.pid=child.pid;writeDB(readDB().map(x=>x.id===s.id?s:x));child.on('exit',()=>writeDB(readDB().map(x=>x.id===s.id?{...x,pid:null}:x)));res.json({ok:true,pid:child.pid})});
app.delete('/api/servers/:id',(req,res)=>{const s=readDB().find(x=>x.id===req.params.id);if(!s)return res.status(404).json({error:'not found'});if(alive(s.pid)){try{process.kill(s.pid)}catch{}};writeDB(readDB().filter(x=>x.id!==s.id));res.json({ok:true})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));app.listen(PORT,HOST,()=>console.log(`mainmet panel on ${HOST}:${PORT}`));
