(()=>{
const WS='wss://mainmet.onrender.com/diccorf';
const AUTH='diccorf.auth.v3', ACCOUNTS='diccorf.accounts.v1', CHATS='diccorf.live.v1';
const $=id=>document.getElementById(id),time=()=>new Date().toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'});
let me=JSON.parse(localStorage.getItem(AUTH)||'null'),sock=null,active=null,tries=0;
let chats=JSON.parse(localStorage.getItem(CHATS)||localStorage.getItem('diccorf.chats.v3')||'null');
let accounts=JSON.parse(localStorage.getItem(ACCOUNTS)||'[]');
if(!Array.isArray(accounts))accounts=[];
if(me&&!accounts.some(a=>a.phone===me.phone)){accounts.push(me);localStorage.setItem(ACCOUNTS,JSON.stringify(accounts))}
if(!Array.isArray(chats)||!chats.length){chats=[{id:'demo1',phone:'demo1',name:'دوست من',online:false,avatar:'د',messages:[{text:'سلام 👋 گفتگوی نمونه',me:false,time:time()}]},{id:'demo2',phone:'demo2',name:'گروه دوستان',online:false,avatar:'گ',messages:[{text:'گروه دوستان آماده است.',me:false,time:time()}]},{id:'support',phone:'support',name:'پشتیبانی Diccorf',online:false,avatar:'D',messages:[{text:'برای چت واقعی، از + شماره دوستت را اضافه کن.',me:false,time:time()}]}]}
function save(){try{localStorage.setItem(CHATS,JSON.stringify(chats));if(me){localStorage.setItem(AUTH,JSON.stringify(me));const i=accounts.findIndex(a=>a.phone===me.phone);if(i>=0)accounts[i]={...accounts[i],...me};else accounts.push(me);localStorage.setItem(ACCOUNTS,JSON.stringify(accounts))}}catch(e){console.warn('Diccorf storage:',e)}}
function persistent(){try{if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});localStorage.setItem('diccorf.storage.ready','1')}catch(e){}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(){const q=($('search')?.value||'').trim().toLowerCase(),box=$('contacts');if(!box)return;box.innerHTML='';chats.filter(c=>(c.name+' '+(c.phone||'')+' '+(c.messages.at(-1)?.text||'')).toLowerCase().includes(q)).forEach(c=>{const e=document.createElement('div');e.className='contact '+(active===c.id?'active':'');e.innerHTML='<div class="avatar">'+(c.photo?'<img src="'+c.photo+'">':esc(c.avatar||c.name[0]||'?'))+'</div><div class="ct"><div class="row"><div class="name">'+esc(c.name)+'</div><div class="time">'+(c.online?'🟢':'')+'</div></div><div class="last">'+esc(c.messages.at(-1)?.text||'گفتگوی جدید')+'</div></div>';e.onclick=()=>open(c.id);box.appendChild(e)})}
function open(id){active=id;const c=chats.find(x=>x.id===id);if(!c)return;$('empty').style.display='none';$('chathead').style.display='flex';$('messages').style.display='flex';$('composer').style.display='flex';$('headName').textContent=c.name;$('headStatus').textContent=c.online?'🟢 آنلاین':'⚪ آفلاین';$('headAvatar').innerHTML=c.photo?'<img src="'+c.photo+'">':esc(c.avatar||c.name[0]||'?');const m=$('messages');m.innerHTML='';c.messages.forEach(x=>{const b=document.createElement('div');b.className='bubble '+(x.me?'me':'them');if(x.image)b.innerHTML='<img src="'+x.image+'"><div>'+esc(x.text||'')+'</div>';else b.textContent=x.text;m.appendChild(b)});m.scrollTop=m.scrollHeight;render();if(c.phone&&!c.phone.startsWith('demo')&&sock?.readyState===1)sock.send(JSON.stringify({type:'history',to:c.phone}));if(innerWidth<=720){$('side').classList.add('hide');$('chat').classList.add('show')}}
function login(){const p=$('phone')?.value.trim(),typedName=$('display')?.value.trim();if(!/^\+?\d{8,15}$/.test(p))return alert('شماره موبایل را درست وارد کن.');let saved=accounts.find(a=>a.phone===p);const n=typedName||saved?.name;if(!n)return alert('نام نمایشی را وارد کن.');me={phone:p,name:n,photo:saved?.photo||null};save();persistent();$('login')?.classList.add('hide');if($('phone'))$('phone').value='';if($('display'))$('display').value='';render();connect()}
function connect(){if(!me||sock?.readyState<=1)return;sock=new WebSocket(WS);$('connection')&&($('connection').textContent='در حال اتصال به چت دوطرفه…');sock.onopen=()=>{tries=0;$('connection')&&($('connection').textContent='🟢 چت دوطرفه فعال است');sock.send(JSON.stringify({type:'hello',phone:me.phone,name:me.name}));};sock.onmessage=e=>{let d;try{d=JSON.parse(e.data)}catch{return}if(d.type==='welcome'){(d.online||[]).forEach(x=>presence(x.phone,x.online));return}if(d.type==='presence'){presence(d.phone,d.online);return}if(d.type==='history'){const c=chats.find(x=>x.phone===d.to);if(c){c.messages=(d.messages||[]).map(x=>({text:x.text,me:x.from===me.phone,time:new Date(x.time).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}));save();if(active===c.id)open(c.id);else render()}return}if(d.type==='message'&&d.message)receive(d.message)};sock.onclose=()=>{sock=null;$('connection')&&($('connection').textContent='🟠 اتصال قطع شد؛ دوباره وصل می‌شوم…');if(me)setTimeout(connect,Math.min(10000,1200*Math.pow(2,tries++)))}}
function presence(phone,on){const c=chats.find(x=>x.phone===phone);if(c){c.online=!!on;save();render();if(active===c.id)$('headStatus').textContent=on?'🟢 آنلاین':'⚪ آفلاین'}}
function receive(m){let c=chats.find(x=>x.phone===m.from);if(!c){c={id:'u_'+m.from,phone:m.from,name:m.from,avatar:m.from.slice(-1),online:true,messages:[]};chats.unshift(c)}c.online=true;c.messages.push({text:m.text,me:false,time:new Date(m.time).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})});save();render();if(active===c.id)open(c.id);else if('Notification'in window&&Notification.permission==='granted')new Notification(c.name,{body:m.text})}
function send(){if(!me)return $('login')?.classList.remove('hide');if(active===null)return;const c=chats.find(x=>x.id===active),t=$('msg')?.value.trim();if(!c||!t)return;if(!c.phone||c.phone.startsWith('demo')){c.messages.push({text:t,me:true,time:time()});save();$('msg').value='';open(c.id);return}if(sock?.readyState!==1)return alert('اتصال چت هنوز برقرار نیست.');sock.send(JSON.stringify({type:'message',to:c.phone,text:t}));c.messages.push({text:t,me:true,time:time()});$('msg').value='';save();open(c.id)}
function add(){if(!me)return $('login')?.classList.remove('hide');const p=prompt('شماره موبایل دوستت را وارد کن:');if(!p||!/^\+?\d{8,15}$/.test(p))return;if(p===me.phone)return alert('شماره خودت را وارد نکن.');const n=prompt('نام دوستت:')||p;let c=chats.find(x=>x.phone===p);if(!c){c={id:'u_'+p,phone:p,name:n,avatar:n[0]||'👤',online:false,messages:[]};chats.unshift(c)}else c.name=n;save();render();open(c.id)}
function setup(){window.openChat=open;window.render=render;window.sendText=send;if($('enter'))$('enter').onclick=login;if($('send'))$('send').onclick=send;if($('plus'))$('plus').onclick=add;if($('search'))$('search').oninput=render;if($('back'))$('back').onclick=()=>{$('side').classList.remove('hide');$('chat').classList.remove('show')};persistent();render();if(!me)$('login')?.classList.remove('hide');else{if($('login'))$('login').classList.add('hide');connect()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();
