(()=>{
const BASE='https://mainmet.onrender.com',AUTH='diccorf.auth.v3',CHATS='diccorf.live.v1',ACCOUNTS='diccorf.accounts.v1';
const $=id=>document.getElementById(id),norm=v=>String(v||'').replace(/[\s()\-]/g,'').trim(),clock=()=>new Date().toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'});
let me=JSON.parse(localStorage.getItem(AUTH)||'null'),active=null,last=Number(localStorage.getItem('diccorf.poll.since')||0),polling=false;
let chats=JSON.parse(localStorage.getItem(CHATS)||'[]'),accounts=JSON.parse(localStorage.getItem(ACCOUNTS)||'[]');
if(!Array.isArray(chats))chats=[];if(!Array.isArray(accounts))accounts=[];
function save(){localStorage.setItem(CHATS,JSON.stringify(chats));if(me){localStorage.setItem(AUTH,JSON.stringify(me));let i=accounts.findIndex(a=>norm(a.phone)===norm(me.phone));if(i<0)accounts.push(me);else accounts[i]={...accounts[i],...me};localStorage.setItem(ACCOUNTS,JSON.stringify(accounts))}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(){const box=$('contacts');if(!box)return;const q=($('search')?.value||'').trim().toLowerCase();box.innerHTML='';chats.filter(c=>(c.name+' '+(c.phone||'')+' '+(c.messages?.at(-1)?.text||'')).toLowerCase().includes(q)).forEach(c=>{const e=document.createElement('div');e.className='contact '+(active===c.id?'active':'');e.innerHTML='<div class="avatar">'+(c.photo?'<img src="'+c.photo+'">':esc(c.avatar||c.name?.[0]||'?'))+'</div><div class="ct"><div class="row"><div class="name">'+esc(c.name)+'</div><div class="time">'+(c.online?'🟢':'')+'</div></div><div class="last">'+esc(c.messages?.at(-1)?.text||'گفتگوی جدید')+'</div></div>';e.onclick=()=>open(c.id);box.appendChild(e)})}
function open(id){active=id;const c=chats.find(x=>x.id===id);if(!c)return;$('empty').style.display='none';$('chathead').style.display='flex';$('messages').style.display='flex';$('composer').style.display='flex';$('headName').textContent=c.name;$('headStatus').textContent=c.online?'🟢 آنلاین':'⚪ آفلاین';$('headAvatar').innerHTML=c.photo?'<img src="'+c.photo+'">':esc(c.avatar||c.name?.[0]||'?');const m=$('messages');m.innerHTML='';(c.messages||[]).forEach(x=>{const b=document.createElement('div');b.className='bubble '+(x.me?'me':'them');b.textContent=x.text||'';m.appendChild(b)});m.scrollTop=m.scrollHeight;render();if(innerWidth<=720){$('side').classList.add('hide');$('chat').classList.add('show')}}
function login(){const p=norm($('phone')?.value),typed=$('display')?.value.trim();if(!/^\+?\d{8,15}$/.test(p))return alert('شماره موبایل را درست وارد کن.');const old=accounts.find(a=>norm(a.phone)===p),name=typed||old?.name;if(!name)return alert('نام نمایشی را وارد کن.');me={phone:p,name,photo:old?.photo||null};save();$('login')?.classList.add('hide');if($('phone'))$('phone').value='';if($('display'))$('display').value='';register();render();poll()}
async function register(){if(!me)return;try{await fetch(BASE+'/diccorf-register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:norm(me.phone),name:me.name})})}catch{}}
function receive(m){let c=chats.find(x=>norm(x.phone)===norm(m.from));if(!c){c={id:'u_'+m.from,phone:m.from,name:m.from,avatar:m.from.slice(-1),online:true,messages:[]};chats.unshift(c)}c.online=true;if(!(c.messages||[]).some(x=>x.id===m.id)){c.messages.push({id:m.id,text:m.text,me:false,time:clock()});save();render();if(active===c.id)open(c.id)}}
async function poll(){if(!me||polling)return;polling=true;try{const u=BASE+'/diccorf-poll?phone='+encodeURIComponent(norm(me.phone))+'&name='+encodeURIComponent(me.name||'')+'&since='+encodeURIComponent(last);const r=await fetch(u,{cache:'no-store'});if(r.ok){const d=await r.json();(d.messages||[]).forEach(receive);last=Number(d.now||Date.now());localStorage.setItem('diccorf.poll.since',String(last))}}catch{}finally{polling=false}}
async function send(){if(!me)return $('login')?.classList.remove('hide');if(active===null)return;const c=chats.find(x=>x.id===active),input=$('msg'),text=input?.value.trim();if(!c||!text)return;if(!c.phone||String(c.phone).startsWith('demo')){c.messages.push({text,me:true,time:clock()});input.value='';save();open(c.id);return}try{const r=await fetch(BASE+'/diccorf-send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from:norm(me.phone),name:me.name,to:norm(c.phone),text})});if(!r.ok)throw Error('send');const d=await r.json();c.messages.push({id:d.message?.id,text,me:true,time:clock()});input.value='';save();open(c.id)}catch{alert('سرور چت در دسترس نیست؛ چند ثانیه دیگر دوباره امتحان کن.')}}
function add(){if(!me)return $('login')?.classList.remove('hide');const p=norm(prompt('شماره موبایل دوستت را وارد کن:'));if(!p||!/^\+?\d{8,15}$/.test(p))return;if(p===norm(me.phone))return alert('شماره خودت را وارد نکن.');const n=prompt('نام دوستت:')||p;let c=chats.find(x=>norm(x.phone)===p);if(!c){c={id:'u_'+p,phone:p,name:n,avatar:n[0]||'👤',online:false,messages:[]};chats.unshift(c)}else c.name=n;save();render();open(c.id)}
function setup(){window.openChat=open;window.render=render;if($('enter'))$('enter').onclick=login;if($('send'))$('send').onclick=send;if($('msg'))$('msg').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};if($('plus'))$('plus').onclick=add;if($('search'))$('search').oninput=render;if($('back'))$('back').onclick=()=>{$('side').classList.remove('hide');$('chat').classList.remove('show')};render();if(me){$('login')?.classList.add('hide');register();poll();setInterval(poll,2000)}else $('login')?.classList.remove('hide')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();
